
language: c

install: 
     - sudo apt-get update
     - sudo apt-get install gcc-arm-embedded python-dev python-pip clang-3.6
     - make config ARCH=arm DEFCONF=stm32f4_def.conf

script: make release


